import { Images } from "./Images";

export const AllData = {
  bestSellers: [
    {
      img: Images.homeProductCard.productCard1,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 1,
    },
    {
      img: Images.homeProductCard.productCard2,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 2,
    },
    {
      img: Images.homeProductCard.productCard3,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 3,
    },
    {
      img: Images.homeProductCard.productCard4,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 4,
    },
    {
      img: Images.homeProductCard.productCard5,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 5,
    },
    {
      img: Images.homeProductCard.productCard6,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 6,
    },
    {
      img: Images.homeProductCard.productCard7,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 7,
    },
    {
      img: Images.homeProductCard.productCard8,
      collection: "Graphic Design",
      product: "English Department",
      price: "$16.48",
      discountedPrice: "$6.48",
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      key: 8,
    },
  ],

  featuredPosts: {
    featured1: {
      img: Images.featuredPosts.featured1,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
    featured2: {
      img: Images.featuredPosts.featured2,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
    featured3: {
      img: Images.featuredPosts.featured3,
      categories: ["Google", "Trending", "New"],
      header: "Loudest à la Madison #1 (L'integral)",
      description:
        "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      date: "22 April 2022",
      comments: "10 comments",
    },
  },
  categories: [
    {
      category: "CLOTHS",
      number: "14 items",
      img: Images.categories.category1,
    },
    {
      category: "JEANS",
      number: "5 items",
      img: Images.categories.category2,
    },
    {
      category: "COATS",
      number: "12 items",
      img: Images.categories.category3,
    },
    {
      category: "SWEATSHIRTS",
      number: "16 items",
      img: Images.categories.category4,
    },
    {
      category: "T-SHIRTS",
      number: "24 items",
      img: Images.categories.category5,
    },
  ],
  productList: [
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList1,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList2,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList3,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList4,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList5,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList6,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList7,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList8,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList9,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList10,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList11,
    },
    {
      name: "Graphic Design",
      category: "English Department",
      price: 16.48,
      discountedPrice: 6.48,
      colors: [
        Images.shapes.ellipses.blueEllipse,
        Images.shapes.ellipses.greenEllipse,
        Images.shapes.ellipses.orangeEllipse,
        Images.shapes.ellipses.blackEllipse,
      ],
      img: Images.productList.productList12,
    },
  ],

  about: [
    {
      img: Images.about.about3,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: ""  ,
      twitter: "",
      key:1,
    },
    {
      img: Images.about.about4,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram:  "",
      twitter: "",
      key:2,
    },
    {
      img: Images.about.about5,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: "",
      twitter: "",
      key:3,
    }
  ],

  team: [
    {
      img: Images.team.team1,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: ""  ,
      twitter: "",
      key:1,
    },
    {
      img:Images.team.team2,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram:  "",
      twitter: "",
      key:2,
    },
    {
      img: Images.team.team3,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: "",
      twitter: "",
      key:3,
    },
    {
      img:Images.team.team4,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: ""  ,
      twitter: "",
      key:4,
    },
    {
      img: Images.team.team5,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram:  "",
      twitter: "",
      key:5,
    },
    {
      img:Images.team.team6,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: "",
      twitter: "",
      key:6,
    },
    {
      img: Images.team.team7,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: ""  ,
      twitter: "",
      key:7,
    },
    {
      img:Images.team.team8,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram:  "",
      twitter: "",
      key:8,
    },
    {
      img: Images.team.team9,
      header: "username",
      role: "professsion",
      facebook: "",
      instagram: "",
      twitter: "",
      key:9,
    }
  ]
};