import { Images } from "./Images";

const BlogData = [
    {
      id: 1,
      img: Images.blog.blog1,
      date: "2 April 2025",
      comments: 18,
      title: "Loudest à la Madison #1 (L'integral)",
      desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      tags: ["Google", "Trending", "New"],
      link: "/feature-posts/detail",
      key:1,
    },
    {
      id: 2,
      img: Images.blog.blog2,
      date: "8 April 2025",
      comments: 12,
      title: "Loudest à la Madison #1 (L'integral)",
      desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      tags: ["Google", "Trending", "New"],
      link: "/feature-posts/detail",
      key:2,
    },
    {
      id: 3,
      img: Images.blog.blog3,
      date: "22 April 2025",
      comments: 21,
      title: "Loudest à la Madison #1 (L'integral)",
      desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
      tags: ["Google", "Trending", "New"],
      link: "/feature-posts/detail",
      key:3,
    },
    {
        id: 4,
        img: Images.blog.blog4,
        date: "2 April 2025",
        comments: 18,
        title: "Loudest à la Madison #1 (L'integral)",
        desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        tags: ["Google", "Trending", "New"],
        link: "/feature-posts/detail",
        key:4,
      },
      {
        id: 5,
        img: Images.blog.blog5,
        date: "8 April 2025",
        comments: 12,
        title: "Loudest à la Madison #1 (L'integral)",
        desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        tags: ["Google", "Trending", "New"],
        link: "/feature-posts/detail",
        key:5,
      },
      {
        id: 6,
        img: Images.blog.blog6,
        date: "22 April 2025",
        comments: 21,
        title: "Loudest à la Madison #1 (L'integral)",
        desc: "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        tags: ["Google", "Trending", "New"],
        link: "/feature-posts/detail",
        key:6,
      },
  ];
  
  export default BlogData;